### ISSUE TITLE
Can this be used with Sass libraries and frameworks?

### ISSUE THREAD

**Issue by CoralSilver** [hugeinc/styleguide#22]
Can Sass libraries and frameworks like Bourbon and Susy be used with this?

**Comment by caiovaccaro** [comment]
Hi @CoralSilver !

Any library that can be imported from source files in the project should work fine. So you would have to download and include the files in the Styleguide, along with importing what you need in your modules.

Let me know if you have any problems, since [Harp](https://github.com/sintaxi/harp) uses a different and fastest way to compile sass files.

Thanks!
